window.COMPI_CONFIG = {
  SUPABASE_URL: 'https://ibepedblciwjxowwyraq.supabase.co',
  SUPABASE_ANON_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliZXBlZGJsY2l3anhvd3d5cmFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTE0MjIxODksImV4cCI6MjEwNjk5ODE4OX0.73tSL9KK319qmoiDhervZZasi06qudBqoI2JI4yxCA8',
  VAPID_PUBLIC_KEY: 'PEGA-AQUI-LA-VAPID-PUBLIC-KEY'
};
