window.COMPI_RESPUESTAS=[
{id:'vida',re:/\b(vida|todo|dia|semana|ano)\b.{0,25}\b(horrible|terrible|fatal|insoportable|porqueria|desastre|pesim\w*)|nada (me )?sale bien|odio mi vida|todo me sale mal/,
 r:['Uf, {n}, eso suena muy pesado. Cuando todo se siente horrible cuesta ver algo más allá. Aquí estoy para escucharte, sin apuro.','Lamento que estés sintiéndote así, {n}. No tienes que tener todo claro ahora; podemos ir de a poquito.','Qué difícil, {n}. Se nota que has cargado con mucho. Gracias por decírmelo.'],
 q:['¿Pasó algo en particular o se fue acumulando?','¿Qué es lo que más te pesa hoy?','Si quieres, cuéntame desde cuándo se siente así.']},
{id:'vacio',re:/\bvacio\b|sin sentido|nada me (importa|emociona|ilusiona)|sin ganas de nada/,
 r:['Esa sensación de vacío agota, {n}, y no necesitas explicarla perfecto para que yo te escuche.','Gracias por ponerlo en palabras, {n}. Sentir que nada te mueve es duro, y vale la pena que no lo cargues solo.'],
 q:['¿Hace cuánto te sientes así?','¿Hay algo, aunque sea pequeño, que antes disfrutabas?'],
 extra:'Si esto dura varios días, hablarlo con un profesional ayuda mucho. Puedes llamar gratis a la Línea 113 (opción 3 y luego 5).'},
{id:'triste',re:/\b(estoy|me siento|ando|me encuentro)\b.{0,12}\b(triste|deprimid\w*|decaid\w*|bajoneado|desanimad\w*|sin animo)\b|ganas de llorar|estuve llorando|me puse a llorar|\btristeza\b/,
 r:['Siento que estés triste, {n}. Está bien no estar bien; aquí puedes contarme sin que nadie te juzgue.','Te leo, {n}, y me importa cómo te sientes. La tristeza también necesita su espacio.','Gracias por confiármelo, {n}. No tienes que animarte a la fuerza conmigo.'],
 q:['¿Quieres contarme qué la provocó?','¿Fue algo de hoy o hace tiempo que lo sientes?','¿Qué te ayudaría más ahora: desahogarte o distraerte un rato?']},
{id:'mal',re:/\b(me siento|estoy|ando)\b.{0,10}\bmal\b|no me siento bien|no estoy bien|me siento raro|me siento rara/,
 r:['Gracias por decírmelo, {n}. A veces uno no sabe ni nombrar lo que siente, y está bien.','Lamento que no estés bien, {n}. Estoy aquí y te escucho.'],
 q:['¿Es más tristeza, cansancio, nervios… o todo mezclado?','¿Quieres contarme qué pasó?']},
{id:'ansiedad',re:/ansios|ansiedad|nervios|nervios[oa]|angusti|panico|me falta el aire|corazon acelerado|preocupad[oa]|no paro de pensar/,
 r:['Eso suena agotador, {n}. Cuando la mente va a mil, a veces ayuda bajar el ritmo del cuerpo primero.','Te entiendo, {n}. La ansiedad hace que todo parezca urgente. Vamos paso a paso.'],
 q:['¿Probamos respirar juntos un minuto? En la pestaña Ánimo hay un ejercicio.','¿Qué es lo que más te preocupa ahora mismo?'],
 extra:'Si se vuelve muy intensa o frecuente, un profesional puede ayudarte bastante.'},
{id:'estres',re:/estres|agobi|abrumad|no doy abasto|demasiadas cosas|mucha presion|sobrecarg|todo se me junto/,
 r:['Suena a que llevas demasiado encima, {n}. Eso cansa a cualquiera.','Cuando todo se junta, ayuda separar lo urgente de lo que puede esperar, {n}.'],
 q:['¿Cuál es lo que más te urge esta semana?','¿Quieres que lo vayamos ordenando y te dejo recordatorios?']},
{id:'cansancio',re:/cansad[oa]|agotad[oa]|sin energia|no tengo energia|no puedo mas|fatiga|quemad[oa]/,
 r:['Se nota que estás agotado, {n}. Tu cuerpo y tu mente también necesitan pausa.','Descansar no es perder el tiempo, {n}. Parece que lo necesitas.'],
 q:['¿Has podido dormir y comer bien estos días?','¿Qué te quita más energía últimamente?']},
{id:'enojo',re:/enojad[oa]|rabia|furios[oa]|molest[oa]|\bharto\b|\bharta\b|fastidi|irritad[oa]|me hizo enojar/,
 r:['Tiene sentido que estés molesto, {n}. Si quieres, desahógate aquí; no te voy a juzgar.','Esa rabia dice que algo te importó o te lastimó, {n}.'],
 q:['¿Qué pasó exactamente?','¿Con quién o con qué estás enojado?']},
{id:'soledad',re:/me siento sol[oa]|estoy sol[oa]|soledad|nadie me (entiende|escucha|quiere|habla)|no tengo amigos|me siento aislad[oa]/,
 r:['Gracias por contármelo, {n}. Sentirse solo duele, y aquí tienes alguien que te escucha.','Lamento que te sientas así, {n}. Mereces compañía y que te escuchen.'],
 q:['¿Hay alguien con quien te gustaría volver a hablar?','¿Desde cuándo sientes esa soledad?'],
 extra:'Y si puedes, escríbele hoy a alguien de confianza, aunque sea algo corto.'},
{id:'miedo',re:/miedo|temor|asustad[oa]|aterrad[oa]|pavor/,
 r:['El miedo puede sentirse enorme, {n}. Lo bueno es que no tienes que enfrentarlo solo.','Te escucho, {n}. Sentir miedo es humano, y hablarlo ya es un paso.'],
 q:['¿A qué le tienes miedo?','¿Qué es lo peor que imaginas que pasaría?']},
{id:'culpa',re:/\bculpa\b|culpable|me arrepiento|remordim|la regue/,
 r:['Cargar con culpa pesa, {n}. Eso habla de que te importa hacer las cosas bien.','Gracias por ser honesto, {n}. Equivocarse no te define.'],
 q:['¿Qué pasó?','¿Qué le dirías a un amigo que se sintiera así?']},
{id:'inseguridad',re:/no sirvo|no soy suficiente|soy un fracaso|me siento inferior|no valgo|inutil|incapaz|no soy capaz/,
 r:['Me duele leer eso, {n}. Ese pensamiento suena muy duro contigo, y no tiene por qué ser la verdad completa.','Eres más que un mal momento, {n}. A veces la mente exagera cuando estamos cansados o heridos.'],
 q:['¿Qué pasó que te hizo sentir así?','¿Qué cosas sí te han salido bien últimamente, aunque sean pequeñas?']},
{id:'estudio',re:/examen|exposicion|parcial|me jalaron|\bjale\b|desaprobe|nota baja|no entiendo (el curso|la clase|el tema)/,
 r:['Los estudios pesan, {n}, y una nota no dice cuánto vales.','Entiendo la presión, {n}. Se puede resolver por partes.'],
 q:['¿Cuándo es lo próximo que debes entregar o rendir? Si quieres, te dejo un recordatorio.','¿Qué parte se te hace más difícil?']},
{id:'relaciones',re:/pele[e]? con|discusion|discuti con|problemas (con|en) (mi|la) (familia|pareja)|mi (mama|papa|madre|padre|pareja|novio|novia|amigo|amiga|hermano|hermana|jefe).{0,30}(me grito|no me entiende|me ignora|se molesto|me dejo)/,
 r:['Los conflictos con gente cercana desgastan, {n}. Gracias por contármelo.','Suena doloroso, {n}. Las discusiones con quienes queremos se sienten más fuerte.'],
 q:['¿Qué fue lo que más te dolió de lo que pasó?','¿Qué te gustaría que pasara ahora?']},
{id:'ruptura',re:/terminamos|me dejo|termine con|rompimos|ruptura|me engano|infiel|\bmi ex\b/,
 r:['Lamento mucho eso, {n}. Una ruptura mueve todo y es normal sentirse revuelto.','Qué golpe, {n}. Date permiso de sentirlo, sin apuro por estar bien.'],
 q:['¿Quieres contarme cómo fue?','¿Cómo te estás sintiendo hoy con todo esto?']},
{id:'duelo',re:/fallecio|murio|fallecimiento|extrano a|perdi a (mi|un)|funeral|velorio/,
 r:['Lo siento muchísimo, {n}. Perder o extrañar a alguien duele de verdad.','Te acompaño en esto, {n}. No hay una forma correcta de sentir una pérdida.'],
 q:['¿Quieres contarme cómo era esa persona?','¿Tienes a alguien cerca con quien compartir lo que sientes?']},
{id:'sueno',re:/no puedo dormir|no duermo|insomnio|duermo mal|duermo poco|desvelad[oa]/,
 r:['Dormir mal desgasta todo, {n}. A veces la mente no se apaga de noche.','Entiendo, {n}. El sueño y el ánimo van muy de la mano.'],
 q:['¿Qué se te viene a la cabeza cuando intentas dormir?','¿Quieres que te ayude a armar una rutina tranquila para la noche?']},
{id:'trabajo',re:/\bmi jefe\b|trabajo.{0,20}(estres|pesado|horrible|cansa)|me despidieron|perdi mi trabajo|me botaron/,
 r:['El trabajo puede sentirse enorme, {n}. Gracias por contármelo.','Entiendo que eso te preocupe, {n}. Vamos viendo qué parte tiene salida.'],
 q:['¿Qué fue lo que más te afectó?','¿Qué necesitas más ahora: desahogarte o pensar en opciones?']},
{id:'futuro',re:/futuro|que voy a hacer con mi vida|no se que estudiar|no se que hacer con mi vida|incertidumbre/,
 r:['No saber qué sigue da vértigo, {n}, pero no tienes que resolver todo hoy.','Es normal sentirse perdido a ratos, {n}. Se aclara paso a paso.'],
 q:['¿Qué cosas sí te gustaría probar?','¿Qué te preocupa más: el dinero, decidir bien o decepcionar a alguien?']},
{id:'feliz',re:/\b(estoy|me siento|ando)\b.{0,10}\b(feliz|contento|contenta|alegre|genial|de buenas|emocionad[oa])\b|me fue (muy )?bien|\blogre\b|\baprobe\b|me felicitaron|buenas noticias/,
 r:['¡Qué alegría leerte así, {n}! 😊 Te lo mereces.','¡Eso es genial, {n}! Disfruta el momento. 🎉','Me alegra mucho, {n}. Se nota que lo disfrutas.'],
 q:['¿Qué fue lo que lo hizo tan bueno?','Cuéntame más, ¿cómo te sentiste?']},
{id:'hablar',re:/necesito (hablar|desahogarme)|quiero (hablar|desahogarme)|puedo hablar contigo|me escuchas/,
 r:['Claro que sí, {n}. Te escucho con calma, sin prisa.','Aquí estoy, {n}. Cuéntame lo que quieras, a tu ritmo.'],
 q:['¿Por dónde quieres empezar?']},
{id:'nose',re:/^(no se|nose|nada|ni idea|no lo se|no se que decir)\W*$/,
 r:['Está bien no saber qué decir, {n}. Podemos quedarnos un ratito así.','No hay apuro, {n}. Si quieres, te pregunto algo sencillo.'],
 q:['¿Cómo dirías que estuvo tu día, del 1 al 10?','¿Qué es lo primero que sentiste al despertar hoy?']},
{id:'regular',re:/^(bien|todo bien|normal|mas o menos|regular|asi nomas|aqui nomas)\W*$/,
 r:['Gracias, {n}. A veces «normal» esconde algo; aquí puedes ser sincero.','Entiendo, {n}. Si más tarde cambia algo, me cuentas.'],
 q:['¿Hubo algo hoy que te hizo sonreír o te molestó?','¿Y de energía cómo vas?']},
{id:'gracias',re:/^(muchas )?gracias\b|te agradezco/,
 r:['Con gusto, {n}. Me alegra acompañarte. 😊','Para eso estoy, {n}. Aquí sigo cuando quieras.']}
];
